- name: users | ana | copy profile image
  tags: dotfiles,dotfiles-ana
  copy:
    src: users/ana/profile_image.png
    dest: /var/lib/AccountsService/icons/ana
    owner: root
    group: root
    mode: 0644

- name: users | ana | check if user has logged in before
  tags: users,ana
  stat:
    path: /var/lib/AccountsService/users/ana
  register: p

- name: users | ana | set profile image
  tags: dotfiles,dotfiles-ana
  lineinfile:
    path: /var/lib/AccountsService/users/ana
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/ana
  when: p.stat.isreg is defined

- name: users | ana | create config/autostart directory
  tags: dotfiles,ana,users
  file:
    path: /home/ana/.config/autostart
    state: directory
    owner: ana
    group: "{{ user_group_name | default('ana') }}"
    mode: 0755
  when: p.stat.isreg is defined

- name: users | ana | enable chrome autostart
  tags: users,ana,google-chrome
  file:
    src: /usr/share/applications/google-chrome.desktop
    dest: /home/ana/.config/autostart/google-chrome.desktop
    owner: ana
    group: "{{ user_group_name | default('ana') }}"
    state: link
  when: p.stat.isreg is defined

# GNOME config
- name: users | ana | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become: true
  become_user: ana
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: users | ana | read favorite apps
  become_user: ana
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: favorite_apps

- name: users | ana | set favorite apps
  tags: gnome,mouse,peripherals
  become_user: ana
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
  when:
    - ansible_distribution == "Fedora"
    - not favorite_apps.value