- name: users | nelu | copy profile image
  tags: dotfiles,dotfiles-nelu
  copy:
    src: users/nelu/profile_image.png
    dest: /var/lib/AccountsService/icons/nelu
    owner: root
    group: root
    mode: 0644

- name: users | nelu | check if user has logged in once
  tags: users,nelu
  stat: 
    path: /var/lib/AccountsService/users/nelu
  register: p

- name: users | nelu | set profile image 
  tags: dotfiles,dotfiles-nelu
  lineinfile:
    path: /var/lib/AccountsService/users/nelu
    regexp: '^Icon='
    line: Icon=/var/lib/AccountsService/icons/nelu
  when: p.stat.isreg is defined

- name: users | nelu | create config/autostart directory
  tags: dotfiles,nelu,users
  file:
    path: /home/nelu/.config/autostart
    state: directory
    owner: nelu
    group: nelu
    mode: 0755
  when: p.stat.isreg is defined

- name: users | nelu | enable chrome autostart
  tags: users,nelu,google-chrome
  file:
    src: /usr/share/applications/google-chrome.desktop
    dest: /home/nelu/.config/autostart/google-chrome.desktop
    owner: nelu
    group: nelu
    state: link
  when: p.stat.isreg is defined 

# GNOME config
- name: users | nelu | enable natural scrolling (mouse)
  tags: gnome,mouse,peripherals
  become: true
  become_user: nelu
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: users | nelu | read favorite apps
  become_user: nelu
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: favorite_apps

- name: users | nelu | set favorite apps
  tags: gnome,mouse,peripherals
  become_user: nelu
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
  when: 
    - ansible_distribution == "Fedora"
    - not favorite_apps.value