# set up flatpak support
- name: software | flatpak | add flatpak support
  package:
    name: flatpak
    state: present

- name: software | flatpak | add flathub remote
  tags: packages,flatpak,workstation-packages
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
