- name: software | google-chrome | add repository (fedora)
  tags: google-chrome,repositories,software,workstation
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- name: software | google-chrome | add repository key (debian)
  tags: google-chrome,repositories,software,workstation
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  when: ansible_os_family == "Debian"

- name: software | google-chrome | add repository (debian)
  tags: google-chrome,repositories,software,workstation
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  notify: refresh_apt_cache
  when: ansible_os_family == "Debian"

- name: software | google-chrome | install package
  package:
    state: present
    name: google-chrome-stable