- name: software | vscode | add repository (fedora)
  tags: vscode,repositories,software,workstation
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- name: software | vscode | add repository key (debian)
  tags: vscode,repositories,software,workstation
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
  when: ansible_os_family == "Debian"

- name: software | vscode | add repository (debian)
  tags: vscode,repositories,software,workstation
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode
  notify: refresh_apt_cache
  when: ansible_os_family == "Debian"

- name: software | vscode | install package
  package:
    state: present
    name: code
