- name: gnome | packages | install gnome packages (all)
  tags: gnome,gnome-packages
  package:
    name:
      - gnome-tweaks
      - seahorse

- name: gnome | packages | install gnome packages (fedora)
  tags: gnome,gnome-packages
  package:
    name:
      - gnome-backgrounds-extras
      - "{{ gnome_extensions_app_package }}"
  when: ansible_distribution == "Fedora"
