# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## install and configure tlp
  - import_tasks: tlp.yml
    when: tlp

  ## set bluetooth controler mode edr only
  - import_tasks: bluetooth.yml

  rescue:
    - set_fact: task_failed=true