
- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - "{{ python_psutil_package }}"

- name: ansible setup | copy ansible_vault_key
  tags: ansible,ansible-setup,ansible-vault
  copy:
    src: ansible/ansible_vault_key
    dest: /root/.ansible_vault_key
    owner: root
    group: root
    mode: 0600

- name: ansible setup | ansible-pull systemd unit files
  tags: ansible,ansible-setup,ansible-pull,systemd
  copy:
    src: ansible/{{ item.src }}
    dest: /etc/systemd/system/{{ item.dest }}
    owner: root
    group: root
    mode: 0640
  with_items:
    - { src: 'ansible_pull_service', dest: 'ansible-pull.service' }
    - { src: 'ansible_pull_timer', dest: 'ansible-pull.timer' }
    - { src: 'ansible_refresh_service', dest: 'ansible-refresh.service' }
    - { src: 'ansible_refresh_timer', dest: 'ansible-refresh.timer' }

- name: ansible setup |  enable ansible systemd timers
  tags: ansible,ansible-setup,ansible-pull,systemd
  systemd:
    name: ansible-{{ item }}.timer
    enabled: true
    masked: false
    daemon_reload: true
  loop:
    - refresh
    - pull