# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
 # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/packages_utilities.yml

  # Make sure users exist on the system
  - import_tasks: users/jeffrey.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/automatic_updates.yml
    when: automatic_updates
  - import_tasks: system_setup/openssh.yml
    when: sshd

  rescue:
    - set_fact: task_failed=true