# Load distro-specific variables
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/packages_utilities.yml

  # Basic user configuration
  - import_tasks: users/ana.yml
    when: user_ana
  - import_tasks: users/jeffrey.yml
  - import_tasks: users/nelu.yml
    when: user_nelu

  # Perform remaining tasks:
  - import_tasks: system_setup/automatic_updates.yml
    when:  automatic_updates
      
  - import_tasks: system_setup/openssh.yml
    when: sshd

  - import_tasks: system_setup/fail2ban.yml
    when: fail2ban

  rescue:
    - set_fact: task_failed=true