- name: system setup | openssh | install or update daemon package
  tags: openssh,ssh,system,settings
  package:
    name: "{{ openssh_package }}"
    state: latest
  notify: restart_sshd

- name: system setup | openssh | enable daemon
  tags: openssh,ssh,system,settings
  service:
    name: "{{ openssh_service }}"
    enabled: yes
    state: started

- name: system setup | openssh | copy custom sshd_config
  tags: openssh,ssh,system,settings
  copy:
    src: system_setup/sshd_config_borcean
    dest: /etc/ssh/sshd_config.d/100-borcean.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd